In [2]:
import numpy as np

In [3]:
A = np.array([1,2,3,4,5,6,7,8,9])

In [4]:
print(A)
print(type(A))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>

In [5]:
B = np.array([[1,2,3],
                           [4,5,6],
                           [7,8,9]])

In [6]:
print(B)
print(type(B))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>

In [7]:
C=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18]]])
print(C)
print(type(C))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
<class 'numpy.ndarray'>

In [8]:
print(A[3])

4

In [9]:
print(B[2,1])

8

In [11]:
print(C[2,2,1])

18

In [13]:
print(C[-1,-1,-1])

18

In [14]:
print(A[1:5])

[2 3 4 5]

In [15]:
#Slice elements from the beginning to 4th element of A
print(A[:5])

#Slice elements from 3rd element to the end of A.
print(A[3:])

#From the 2nd element of B, slice elements from 2 to 3.
print(B[2,2:4])

#Crete an array fruit that contains names of the fruits.
fruit = np.array(['banana','apple','cherry','orange'])


#Reshape array A into a new 2-D array A1.
A1 = A.reshape(3,3)

#Flatten the array C.
C1 = C.reshape(-1)

#Iterate through all elements of A to print them.
for x in A:
    print(x)

#Iterate through all elements of B to print them.
for i in B:
    for j in i:
         print(j)

#Iterate through all elements of C to print them.
for i in C:
    for j in i:
        for k in j:
            print(k)

#Create an array A3 from A, where all elements of A3 are 5 times elements of A.  Join A and A3 into A3
A3 = 5*A
print(A)
print(A3)
A3 = np.concatenate((A,A3))

#Create two 2-D arrays and perform element wise multiplication.
P = np.array([[1,2,3],
             [4,5,6]])
Q = np.array([[2, -7, 5],
              [-6, 2, 0]])
R = np.multiply(P,Q)

#Create two 2-D arrays and perform multiplication.
P = np.array([[1,2,3],
        		[4,5,6]])
Q = np.array([[2, -7],
              		[-6, 2],
              		[1,5]])
R = np.dot(P,Q)

#Find square of all elements of B.
np.square(B)

#Find addition of all elements of C.
np.sum(C)
#Find 1/√(ex-1) for all elements of C, where x is an elements of C.
print(np.reciprocal(np.sqrt((np.exp(C)-1))))

#Install and import pandas
import pandas as pd

[1 2 3 4 5]
[4 5 6 7 8 9]
[9]
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
[1 2 3 4 5 6 7 8 9]
[ 5 10 15 20 25 30 35 40 45]
[[[7.62873978e-01 3.95623107e-01]
  [2.28901063e-01 1.36591948e-01]
  [8.23629462e-02 4.98488882e-02]]

 [[3.02111611e-02 1.83187118e-02]
  [1.11096821e-02 6.73809996e-03]
  [4.08680557e-03 2.47875979e-03]]

 [[1.50344089e-03 9.11882345e-04]
  [5.53084455e-04 3.35462647e-04]
  [2.03468373e-04 1.23409805e-04]]]

In [2]:
import pandas as pd
df = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/nba.csv')

In [3]:
#Display top 10 rows of the data.
df.head(10)

#Find the deatails of the data in datafrme.
df.info()

#Display ‘Team’ column of the data.
df['Team']

#Find the details of the 10th entry of dataframe.
df.iloc[9]

#Display the details of the player whose age is greater than 25.
df[df['Age']>25]

#Display the details of the player whose age is greater than 25 and belongs to team Bolton Celtics or Utah Jazz.
df[df['Age']>25 & df['Team'].isin(['Bolton Celtics','Uttah Jazz'])]

#Check if any empty cell is in the dataframe. Find the row with an empty name entry and remove if any.
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64